create table if not exists public.generated_questions (
  id                bigint generated by default as identity primary key,
  source_table      text not null check (source_table in ('book_contents','movie_quotes_ko_en')),
  source_id         text not null,
  question_type     text not null check (question_type in ('fill_blank','word_order','translation_match')),
  work_title        text not null,
  author            text not null,
  prompt            text not null,
  prompt_korean     text,
  sentence          text not null,
  options           jsonb not null,
  correct_answer    jsonb not null,
  explanation       text not null,
  validation_status text not null default 'passed',
  validation_notes  text,
  review_status     text not null default 'drafted',
  created_at        timestamptz not null default now()
);

alter table public.generated_questions enable row level security;

-- anon은 읽기만 (contentService.ts가 승인된 AI 문제를 조회해야 함).
-- 쓰기는 전부 admin-review Edge Function의 service_role 경유로만 이루어진다.
create policy "anon read generated_questions"
  on public.generated_questions for select to anon
  using (true);
